name: watch_store_app
description: "Watch Store with Flutter..."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - "assets/images/patek_1.jpg"
    - "assets/images/patek_2.jpg"
    - "assets/images/patek_3.jpg"
    - "assets/images/seiko_1.png"
    - "assets/images/seiko_2.png"
    - "assets/images/swatch_1.png"
    - "assets/images/swatch_2.png"
    - "assets/images/swatch_3.jpg"